CUDA_VISIBLE_DEVICES=0 python finetune.py \
  --model_name '../../models/falcon-7b' \
  --data_path './news_emotion_1k.json' \
  --output_dir './output' \
  --load_4bit \
  --batch_size 16 \
  --micro_batch_size 4 \
  --num_epochs 50 \
  --save_step 1 \
  --learning_rate 3e-4 \
  --adapter_name 'lora'