python finetune.py \
  --model_name '/home/lib/models/falcon-7b' \
  --data_path './news_emotion_1k.json' \
  --output_dir './output' \
  --load_4bit \
  --batch_size 16 \
  --micro_batch_size 4 \
  --num_epochs 50 \
  --save_step 1 \
  --report ['tensorboard'] \
  --learning_rate 3e-4 \
  --use_lora \
  --lora_target_modules ['query_key_value']